apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifest/resourcedefinition.yaml
  - manifest/serviceaccount.yaml
  - manifest/clusterrole.yaml
  - manifest/clusterrolebinding.yaml
  - manifest/deployment.yaml

namespace: exercises
images:
  - name: PROJECT/CONTROLLER
    newName: kuzn2k/dummysite-controller:1.0.0
