apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: ping-pong-db-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-db-server
  template:
    metadata:
      labels:
        app: ping-pong-db-server
    spec:
      containers:
        - name: app
          image: kuzn2k/ping-pong-server:1.0.6
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "3000"
            - name: PGHOST
              value: "postgress-svc"
            - name: PGPORT
              value: "5432"
            - name: PGUSER
              value: "postgres"
            - name: PGPASSWORD
              value: ""
            - name: PGDATABASE
              value: "postgres"
          ports:
            - name: ping-port
              containerPort: 3000
