apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: exercises
  name: ping-server-ingress
spec:
  rules:
  - http:
      paths:
        - path: /pingpong
          pathType: Prefix
          backend:
            service:
              name: ping-pong-service-svc
              port:
                number: 2345
        - path: /pings
          pathType: Prefix
          backend:
            service:
              name: ping-pong-service-svc
              port:
                number: 2345