apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: ping-pong-service-svc
spec:
  type: LoadBalancer
  selector:
    app: ping-pong-db-server
  ports:
    - port: 80
      protocol: TCP
      targetPort: ping-port
