apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: ping-pong-service-svc
spec:
  type: ClusterIP
  selector:
    app: ping-pong-db-server
  ports:
    - port: 2345
      protocol: TCP
      targetPort: ping-port
