apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-server
  template:
    metadata:
      labels:
        app: ping-pong-server
    spec:
      volumes:
        - name: shared-files
          persistentVolumeClaim:
            claimName: app-storage-claim
      containers:
        - name: app
          image: kuzn2k/ping-pong-server:1.0.1
          imagePullPolicy: Always
          volumeMounts:
            - name: shared-files
              mountPath: /var/tmp/mooc/files 
          env:
            - name: PORT
              value: "3000"
          ports:
            - name: ping-port
              containerPort: 3000
