apiVersion: v1
kind: Namespace
metadata:
  name: ex1-4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-server
  namespace: ex1-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-server
  template:
    metadata:
      labels:
        app: todo-server
    spec:
      containers:
        - name: app
          image: kuzn2k/ex1.2-todo-server:1.0.0
