apiVersion: v1
kind: Service
metadata:
  name: todo-svc
spec:
  type: NodePort
  selector:
    app: todo-server
  ports:
    - name: http
      nodePort: 30080
      protocol: TCP
      port: 3000
      targetPort: todo-port
