apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: wiki-stub-svc
spec:
  type: ClusterIP
  selector:
    app: wiki-stub
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
