apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifest/config.yaml
- manifest/persistentvolumeclaim.yaml
- manifest/statefullset.yaml
- manifest/ping-deployment.yaml
- manifest/ping-service.yaml
- manifest/random-deployment.yaml
- manifest/random-app-service.yaml
- manifest/gateway.yaml
- manifest/route.yaml
  
images:
- name: PROJECT/BACKEND
  newName: kuzn2k/ping-pong-server
  newTag: 16da861910558993685e5b00265f63d33370402d
- name: PROJECT/LOGOUTPUT
  newName: kuzn2k/log-output
  newTag: 16da861910558993685e5b00265f63d33370402d
- name: PROJECT/WWW
  newName: kuzn2k/random-server
  newTag: 16da861910558993685e5b00265f63d33370402d
