apiVersion: v1
kind: ConfigMap
metadata:
  namespace: exercises
  name: log-output-config
data:
  message: "hello from kube"
  information.txt: |
    Very important information from file
  greeting_host: "http://random-server-gateway-istio.exercises.svc.cluster.local"
  pingpong_host: "http://random-server-gateway-istio.exercises.svc.cluster.local"
  