apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: greeter-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter-v2
  template:
    metadata:
      labels:
        app: greeter-v2
    spec:
      containers:
        - name: app
          image: PROJECT/GREETER
          imagePullPolicy: Always
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
               path: /healthz
               port: 3000
          env:
            - name: PORT
              value: "3000"
            - name: MESSAGE
              value: "Hello from version 2"
          ports:
            - name: greeter-port
              containerPort: 3000
