apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: ping-pong-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-server
  template:
    metadata:
      labels:
        app: ping-pong-server
    spec:
      containers:
        - name: app
          image: PROJECT/BACKEND
          imagePullPolicy: Always
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
               path: /healthz
               port: 3000          
          env:
            - name: PORT
              value: "3000"
            - name: PGHOST
              value: "postgress-svc"
            - name: PGPORT
              value: "5432"
            - name: PGUSER
              value: "postgres"
            - name: PGPASSWORD
              value: ""
            - name: PGDATABASE
              value: "postgres"
          ports:
            - name: ping-port
              containerPort: 3000
