apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: random-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: random-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  template:
    metadata:
      labels:
        app: random-server
    spec:
      volumes:
        - name: shared-files
          persistentVolumeClaim:
            claimName: app-storage-claim
        - name: config
          configMap:
            name: log-output-config
            items:
            - key: "information.txt"
              path: "information.txt"            
      containers:
        - name: endpoint
          image: PROJECT/WWW
          imagePullPolicy: Always
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
               path: /healthz
               port: 3000
          env:
            - name: PORT
              value: "3000"
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-config
                  key: message
            - name: GREETING_HOST
              valueFrom:
                configMapKeyRef:
                  name: log-output-config
                  key: greeting_host
            - name: PINGPONG_HOST
              valueFrom:
                configMapKeyRef:
                  name: log-output-config
                  key: pingpong_host
          volumeMounts:
            - name: shared-files
              mountPath: /var/tmp/mooc/files
            - name: config
              mountPath: "/config"
              readOnly: true              
        - name: log-output
          image: PROJECT/LOGOUTPUT
          imagePullPolicy: Always
          volumeMounts:
            - name: shared-files
              mountPath: /var/tmp/mooc/files
             
