apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-config
data:
  todos_url: "/todos"
  image_url: "/image"
  data_root: "/var/tmp/mooc/files"
  tmp_image_file: "current-image.jpg"
  image_service_url: "https://picsum.photos/"
  image_size: "1200"
  max_todo_length: "140"
  refresh_time: "600"
  db_url: "todo-postgres-svc"
  db_port: "5432"
  db_user: "postgres"
  db_database: "postgres"
  gcs_bucket: "mooc-project-backup"
  backend_probe_url: "http://todo-bc-svc:2345/healthz"
  nats_url: "nats://nats:4222"
  nats_subject: "todos.events"
  nats_queue: "broadcaster"

  
