apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: todo-svc
spec:
  type: ClusterIP
  selector:
    app: todo-server
  ports:
    - port: 2345
      protocol: TCP
      targetPort: todo-port
