apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifest/config.yaml
- manifest/persistentvolumeclaim.yaml
- manifest/statefullset.yaml
- manifest/ping-deployment.yaml
- manifest/ping-service.yaml
- manifest/greeter-v1-deployment.yaml
- manifest/greeter-v2-deployment.yaml
- manifest/greeter-v1-service.yaml
- manifest/greeter-v2-service.yaml
- manifest/random-deployment.yaml
- manifest/random-app-service.yaml
- manifest/random-server-gateway.yaml
- manifest/random-server-route.yaml
  
images:
  - name: PROJECT/WWW
    newName: kuzn2k/random-server:1.0.9
  - name: PROJECT/BACKEND
    newName: kuzn2k/ping-pong-server:1.0.9
  - name: PROJECT/LOGOUTPUT
    newName: kuzn2k/log-output:1.0.1
  - name: PROJECT/GREETER
    newName: kuzn2k/greeter-server:1.0.0

