apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: app
          image: kuzn2k/todo-backend:1.0.4
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "3000"
            - name: TODOS_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: todos_url
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: db_url
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: db_port
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-app-secret
                  key: db_password
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: db_database
          ports:
            - name: todo-bc-port
              containerPort: 3000
