apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  template:
    metadata:
      labels:
        app: todo-server
    spec:
      volumes:
        - name: shared-files
          persistentVolumeClaim:
            claimName: app-storage-claim    
      containers:
        - name: app
          image: PROJECT/WWW
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "5m"
              memory: "20Mi"
            limits:
              cpu: "150m"
              memory: "30Mi"
          volumeMounts:
            - name: shared-files
              mountPath: /var/tmp/mooc/files          
          env:
            - name: PORT
              value: "3000"
            - name: TODOS_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: todos_url
            - name: IMAGE_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: image_url
            - name: DATA_ROOT
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: data_root  
            - name: TMP_IMAGE_FILE
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: tmp_image_file
            - name: IMAGE_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: image_service_url
            - name: IMAGE_SIZE
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: image_size
            - name: MAX_TODO_LENGTH
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: max_todo_length
            - name: REFRESH_TIME
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: refresh_time
          ports:
            - name: todo-port
              containerPort: 3000
