apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifest/config.yaml
  - manifest/persistentvolumeclaim.yaml
  - manifest/statefullset.yaml
  - manifest/todo-app-deployment.yaml
  - manifest/todo-app-service.yaml
  - manifest/todo-backend-horizontalpodautoscaler.yaml  
  - manifest/todo-backend-deployment.yaml
  - manifest/todo-backend-service.yaml
  - manifest/nats-deployment.yaml
  - manifest/nats-service.yaml
  - manifest/broadcaster-deployment.yaml
  - manifest/broadcaster-horizontalpodautoscaler.yaml
  - manifest/cronjobs.yaml
  - manifest/gateway.yaml
  - manifest/route.yaml
    
generators:
  - secrets/ksops.yaml

generatorOptions:
  disableNameSuffixHash: true



