name: Release application

on:
  push:

env:
  SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north2-c
  REGISTRY: europe-north2-docker.pkg.dev
  REPOSITORY: mooc
  IMAGE_WWW: todo-server
  SERVICE_WWW: todo-server
  IMAGE_BACKEND: todo-backend
  SERVICE_BACKEND: todo-backend
  IMAGE_REMINDER: todo-reminder
  SERVICE_REMINDER: todo-reminder-job  
  BRANCH: ${{ github.ref_name }}

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2

      - name: 'Use gcloud CLI'
        run: gcloud info   

      - run: gcloud --quiet auth configure-docker $REGISTRY

      - name: 'Get GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'

      - name : 'Form the image name'
        run: |-
          echo "IMAGE_WWW_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE_WWW:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV
          echo "IMAGE_BACKEND_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE_BACKEND:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV
          echo "IMAGE_REMINDER_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE_REMINDER:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV

      - name: Build WWW
        working-directory: ./todo-app/todo-server
        run: docker build --tag $IMAGE_WWW_TAG .

      - name: Publish WWW
        working-directory: ./todo-app/todo-server
        run: docker push $IMAGE_WWW_TAG

      - name: Build BACKEND
        working-directory: ./todo-app/todo-backend
        run: docker build --tag $IMAGE_BACKEND_TAG .

      - name: Publish BACKEND
        working-directory: ./todo-app/todo-backend
        run: docker push $IMAGE_BACKEND_TAG

      - name: Build REMINDER
        working-directory: ./todo-app/todo-reminder
        run: docker build --tag $IMAGE_REMINDER_TAG .

      - name: Publish REMINDER
        working-directory: ./todo-app/todo-reminder
        run: docker push $IMAGE_REMINDER_TAG  

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0

      - name: Install sops
        run: |
          set -euo pipefail
          SOPS_VER=3.11.0
          curl -L -o /usr/local/bin/sops \
            https://github.com/getsops/sops/releases/download/v${SOPS_VER}/sops-v${SOPS_VER}.linux.amd64
          chmod +x /usr/local/bin/sops
          sops --version

      - name: Install ksops and register Kustomize plugin
        run: |
          set -euo pipefail

          curl -s https://raw.githubusercontent.com/viaduct-ai/kustomize-sops/master/scripts/install-ksops-archive.sh | bash

          export KUSTOMIZE_PLUGIN_HOME="$HOME/.config/kustomize/plugin"
          mkdir -p "$KUSTOMIZE_PLUGIN_HOME/viaduct.ai/v1/ksops"
          cp /usr/local/bin/ksops "$KUSTOMIZE_PLUGIN_HOME/viaduct.ai/v1/ksops/ksops"
          chmod +x "$KUSTOMIZE_PLUGIN_HOME/viaduct.ai/v1/ksops/ksops"

          ls -la "$KUSTOMIZE_PLUGIN_HOME/viaduct.ai/v1/ksops"

      - name: Deploy
        working-directory: ./todo-app
        env:
          KUSTOMIZE_PLUGIN_HOME: ${{ env.HOME }}/.config/kustomize/plugin
        run: |-
          kustomize edit set image PROJECT/WWW=$IMAGE_WWW_TAG
          kustomize edit set image PROJECT/BACKEND=$IMAGE_BACKEND_TAG
          kustomize edit set image PROJECT/REMINDER=$IMAGE_REMINDER_TAG
          kustomize build . --enable-alpha-plugins --enable-exec | kubectl apply -f -
          kubectl rollout status deployment $SERVICE_WWW -n project
          kubectl rollout status deployment $SERVICE_BACKEND -n project
          kubectl get services -o wide -n project
          kubectl get pod -o wide -n project
          kubectl get gateway -o wide -n project
